---
name: CI
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  unlimited:
    name: Run build and unit tests. (unlimited API)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-setuptools python3-dev libsystemd-dev \
            systemd dbus python3 gcc
      - name: Build extension
        run: |
          python3 setup.py build --build-lib build-lib
      - name: Run unit tests
        run: |
          PYTHONPATH=./build-lib python3 -m unittest --verbose
  limited:
    name: Run build and unit tests. (limited API)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-setuptools python3-dev libsystemd-dev \
            systemd dbus python3 gcc pkg-config
      - name: Build extension
        env:
          PYTHON_SDBUS_USE_LIMITED_API: "1"
        run: |
          python3 setup.py build --build-lib build-lib
      - name: Run unit tests
        run: |
          PYTHONPATH=./build-lib python3 -m unittest --verbose
  lint:
    name: Run linters on the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3 python3-pip meson
          sudo pip3 install --upgrade mypy isort flake8 pyflakes pycodestyle \
                                      jinja2 Sphinx types-setuptools
      - name: Run linters
        run: |
          meson setup build
          ninja -C build lint-python
  alpine:
    name: Alpine Linux test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Build Alpine container
        run: |
          podman build --tag alpine-ci -f ./test/containers/Containerfile-alpine .
      - name: Test unlimited API
        run: |
          podman run --rm alpine-ci
      - name: Test limited API
        run: |
          podman run --env PYTHON_SDBUS_USE_LIMITED_API=1 --rm alpine-ci
